#!/usr/bin/env bash

if (( force_flag <= 0 )) && path_exists "/etc/nginx"
then
  error "/etc/nginx already exists, in order to re-configure pass the --force flag"
else
  ensure_paths_exist "/etc/nginx"
  copy_paths "${install_path}/etc/nginx/" to "/etc/nginx"
fi
