#!/usr/bin/env bash

(( force_flag )) || ! path_exists "/etc/nginx" ||
  error "/etc/nginx already exists, in order to re-configure pass the --force flag"

ensure_paths_exist "/etc/nginx"

cp -Rf "${install_path}"/etc/nginx/* "/etc/nginx/"

