#!/usr/bin/env bash

nginx_postinstall()
{
  enter "${install_path}"
  ensure_paths_exist "${nginx_dirs[@]}"

  enter "${install_path}/etc/nginx"
  ensure_paths_exist "${config_dirs[@]}"

  # Cleanup default nginx install messy directory.
  move_files --if-exists "${nginx_files[@]}" to "${install_path}/etc/nginx/conf" \
   from "${install_path}/etc/nginx"

  ensure_paths_exist "${install_path}/config" "${install_path}/etc/nginx/servers"

}

nginx_postactivate()
{
  if user_is_root
  then
    if (( ${force_flag:=0} == 1 ))
    then
      remove_paths "${service_config_path}"
    fi

    if ! file_exists "${service_config_path}/nginx.conf"
    then
      link --force "${install_base_path}/active/etc/nginx" \
        "${service_config_path}"

      enter "${service_config_path}"

      # TODO: add from parameter from remove_files
      remove_files "${nginx_files[@]}"
    fi

    link --force "${install_base_path}/active/sbin/nginx" \
      "${active_path}/sbin/nginx"
  fi
}


