#!/usr/bin/env bash

nginx_cli()
{
  local _ignored_args=() _package_args=( $@ ) _token index \
    _count=${#_package_args[@]} _domain

  variable_is_nonempty domains || domains=()

  for (( index=0 ; index < $_count ; index++ ))
  do
    _token="${_package_args[$index]}"

    case "${_token}" in
      domain)
        _domain="${_package_args[$((++index))]}"
        _domain="${_domain//,/ }"
        variable_is_nonempty _domain ||
          error "$FUNCNAME: a domain must follow keyword 'domain'"
        domains+=(${_domain})
        ;;
      user)
        project_user="${_package_args[$((++index))]}"
        variable_is_nonempty project_user ||
          error "$FUNCNAME: a project user name must follow keyword 'user'"
        ;;
      project)
        project="${_package_args[$((++index))]}"
        variable_is_nonempty project ||
          error "$FUNCNAME: a project name must follow keyword 'project'"
        ;;
      edit)
        edit_flag=1
        ;;
      *)
        _ignored_args+=("${_token}")
        ;;
    esac

  done

  nginx_initialize "${_ignored_args[@]}"
}

nginx_initialize()
{
  if ! string_contains "{FUNCNAME[*]}" "extension_action_prerequisites"
  then
    string_contains "{FUNCNAME[*]}" "package_cli"        || package_cli
    string_contains "{FUNCNAME[*]}" "service_initialize" || service_initialize
  fi

  # TODO: Allow overriding of these parameters via cli
  # These defaults may be overridden also by the nginx configuration files.
  configure_flags+=(
  --prefix="${install_path}"
  --conf-path="${install_path}/etc/nginx/nginx.conf"
  --sbin-path="${install_path}/sbin/nginx"
  --pid-path="${install_path}/run/nginx.pid"
  --lock-path="${install_path}/run/nginx.lock"
  --http-client-body-temp-path="${install_path}/spool/client_body_temp"
  --http-proxy-temp-path="${install_path}/spool/proxy_temp"
  --http-fastcgi-temp-path="${install_path}/spool/fastcgi_temp"
  --http-log-path="${install_path}/log/access.log"
  --error-log-path="${install_path}/log/error.log"
  --with-http_ssl_module
  --with-http_stub_status_module
  )
  # TODO: Add a CLI --imap flag
  # --with-imap
  # --with-imap_ssl_module

  for library in zlib pcre # openssl
  do
    if package_is_active "$library"
    then
      configure_flags+=( --with-${library}="${packages_path}/${library}/active/src" )
    fi
  done
  unset library

  config_dirs=( conf servers users ssl )
  nginx_dirs=( log spool run lock etc/nginx tmp )

  nginx_files=( fastcgi.conf fastcgi.conf.default fastcgi_params
  fastcgi_params.default koi-utf koi-win mime.types mime.types.default
  nginx.conf.default scgi_params scgi_params.default uwsgi_params
  uwsgi_params.default win-utf
  )

  LDFLAGS="-L${active_path}/lib ${LDFLAGS:-}"
  CFLAGS="-I${active_path}/include ${CFLAGS:-} "

  true \
    ${edit_flag:=0} \
    ${project_user:=${project}} \
    ${project_path:="/home/${project_user:-${project}}"} \
    ${domains:=("${project}.com" "*${project}.com")}

  master_pid="$(ps auxww | awk '/[n]ginx: master/{print $2}' | head -1)"
  service_flags=( -c "${service_config_path}/nginx.conf" )
  service_binary="${install_path}/sbin/nginx"

  user_is_not_root || service_run_as_root_flag=1
}

nginx_install_dependencies()
{
  warn "${action} is untested / unused thus far."

  if os_is_linux
  then
    if command_exists pacman
    then
      pacman -S --noconfirm patch curl zlib pcre openssl make base-devel

    elif command_exists apt-get
    then
      apt-get install build-essential openssl curl zlib1g zlib1g-dev libssl-dev pcre pcre-dev

    elif command_exists yum
    then
      yum install -y gcc-c++ patch zlib zlib-devel openssl openssl-devel pcre pcre-devel

    elif command_exists emerge
    then
      log "TODO: Tell wayne how to install pcre, openssl and zlib dev headers on gentoo."

    else
      log "TODO: Install zlib openssl pcre via curl, complile install."

    fi
  elif os_is_darwin
  then
    release="( $(sw_vers -productName) )"
    log "Notes for ${system} $release for OSX be sure to have the latest XCode tools. "
  fi
  echo
}

nginx_postinstall()
{
  if file_exists "nginx.conf"
  then
    move_file "nginx.conf" \
      to "${install_path}/etc/nginx/conf/nginx.conf.default" \
      from "${install_path}/etc/nginx"
  fi

  enter "${install_path}"
  ensure_paths_exist "${nginx_dirs[@]}"

  enter "${install_path}/etc/nginx"
  ensure_paths_exist "${config_dirs[@]}"

  # Cleanup default nginx install messy directory.
  move_files --if-exists "${nginx_files[@]}" \
    to "${install_path}/etc/nginx/conf" \
    from "${install_path}/etc/nginx"

  ensure_paths_exist "${install_path}/config" "${install_path}/etc/nginx/servers"
}

nginx_postactivate()
{
  user_is_root || return 0

  (( ${force_flag:=0} == 0 )) || remove_paths "${service_config_path}"

  service_setup # create user, etc... then calls nginx_service_setup

  if ! file_exists "${service_config_path}/nginx.conf"
  then
    link force from "${install_path}/etc/nginx" to "${service_config_path}"

    enter "${service_config_path}"

    remove_files "${nginx_files[@]}"
  fi

  link force from "${install_path}/sbin/nginx" to "${active_path}/sbin/nginx"
}

nginx_service_setup()
{
  install_template "nginx/nginx.conf" \
    to "${install_path}/etc/nginx/nginx.conf" \
    mode 0644 owner "${service_user}"

  seed_template "${install_path}/etc/nginx/nginx.conf" \
    modules_path "${modules_path}" \
    service "${service}" \
    service_user "${service_user}" \
    service_config_path "${service_config_path}" \
    service_pid_file "${service_pid_file}" \
    service_log_path "${service_log_path}"

  ensure_paths_exist "${install_path}/etc/nginx/health/"

  install_template "nginx/nginx.health" \
    to "${install_path}/etc/nginx/health/nginx.conf" \
    mode 0644 owner "${service_user}"

  install_template "nginx/nginx" to "${install_path}/etc/nginx" \
    mode 0755 owner "${service_user}"

  templates=( "mime.types" "proxy.conf" )

  for template in "${templates[@]}"
  do
    install_template "nginx/${template}" \
      to "${install_path}/etc/nginx/conf/${template}" \
      mode 0644 owner "${service_user}"
  done

  enter "${install_path}"

  replace_content "^user .*;$" with "# No user line for non-root installs "\
    in "${install_path}/etc/nginx/nginx.conf"

  chown_paths --recursive "${service_user}" "${nginx_dirs[@]}" "etc/nginx"
}

nginx_list()
{
  local master_list=("$(ps auxww | head -1)") worker_list=()

  if (( master_pid > 0 ))
  then
    while read -r line
    do
      if [[ "$line" =~ nginx ]]
      then
        if [[ "$line" =~ master ]]
        then
          master_list+=("${line}")
        elif [[ "$line" =~ worker ]]
        then
          worker_list+=("${line}")
        fi
      fi
    done < <(ps auxww | awk '/[n]ginx/')

    array_join master_list "\n"
    echo
    array_join worker_list "\n"
    echo
  else
    log "No Nginx master processes was found."
  fi
}

nginx_configure_root_etc()
{
  (( force_flag )) || ! path_exists "/etc/nginx" ||
    error "/etc/nginx already exists, in order to re-configure pass the --force flag"

  ensure_paths_exist "/etc/nginx"

  cp -Rf "${install_path}"/etc/nginx/* "/etc/nginx/"
}

nginx_conf_edit()
{
  if command_exists vim
  then
    ${EDITOR:=vim}
  else
    ${EDITOR:=vi}
  fi
  export EDITOR

  ${EDITOR} "${service_config_path}/nginx.conf"
}

nginx_server_conf_edit()
{
  if command_exists vim
  then
    ${EDITOR:=vim}
  else
    ${EDITOR:=vi}
  fi

  ${EDITOR} "${service_config_path}/servers/${project:-"${extension_args[0]}"}.conf"
}

nginx_server_new_cli()
{
  variable_is_nonempty project || array_shift extension_args project
  true ${project:=$1}
  variable_is_nonempty project || fail "$FUNCNAME: project name must be given."
  nginx_cli
}

nginx_server_new()
{
  template_exists "nginx/server.conf" ||
    fail "$FUNCNAME: $extension_templates_path/server.conf template is missing."

  ensure_paths_exist "${service_config_path}/servers"

  # If this is running as root, ensure that Nginx can read from the
  # application directory.
  if user_is_root && path_exists "/home/${project}"
  then
    chmod_paths --recursive 'g+rx' "/home/${project}"
  fi

  project_config="${service_config_path}/servers/${project}.conf"

  if (( force_flag == 1 )) && file_exists "${project_config}"
  then
    remove_file "${project_config}"
  fi

  file_exists "${project_config}" ||
    install_template "nginx/server.conf" to "${project_config}"

  ! file_exists "${project_config}" ||
    seed_template "${project_config}" \
      modules_path "${modules_path}" \
      service "${service}" \
      project "${project}" \
      domains "${domains[*]}" \
      project_path "${project_path}" \
      project_user "${project_user}" \
      service_config_path "${service_config_path}" \
      service_pid_file "${service_pid_file}" \
      service_log_path "${service_log_path}"
}
