#!/usr/bin/env bash

# TODO: Allow overriding of these parameters via cli
# These defaults may be overridden also by the nginx configuration files.
configure_flags=(
--prefix="${install_path}"
--conf-path="${install_path}/etc/nginx/nginx.conf"
--sbin-path="${install_path}/sbin/nginx"
--pid-path="${install_path}/run/nginx.pid"
--lock-path="${install_path}/run/nginx.lock"
--http-client-body-temp-path="${install_path}/spool/client_body_temp"
--http-proxy-temp-path="${install_path}/spool/proxy_temp"
--http-fastcgi-temp-path="${install_path}/spool/fastcgi_temp"
--http-log-path="${install_path}/log/access.log"
--error-log-path="${install_path}/log/error.log"
--with-http_ssl_module
--with-http_stub_status_module
)
# TODO: Add a CLI --imap flag
# --with-imap
# --with-imap_ssl_module

for library in zlib pcre # openssl
do
  if package_is_active "$library"
  then
    configure_flags+=( --with-${library}="${packages_path}/${library}/active/src" )
  fi
done
unset library

config_dirs=( conf servers users ssl )
nginx_dirs=( log spool run lock etc/nginx tmp )

nginx_files=( fastcgi.conf fastcgi.conf.default fastcgi_params
fastcgi_params.default koi-utf koi-win mime.types mime.types.default
nginx.conf.default scgi_params scgi_params.default uwsgi_params
uwsgi_params.default win-utf
)

LDFLAGS="-L${active_path}/lib ${LDFLAGS:-}"
CFLAGS="-I${active_path}/include ${CFLAGS:-} "

master_pid="$(ps auxww | awk '/[n]ginx: master/{print $2}' | head -1)"
service_flags=( -c "${service_config_path}/nginx.conf" )
service_binary="${active_path}/sbin/nginx"

user_is_not_root || service_run_as_root_flag=1

