.\"   $Id$
.\"
.\"   Man page for the bdsm project.
.\"
.\"   $Log$
.\"

.TH SM 1 "2011 October 27" "SM Framework"

.SH SYNOPSIS
.B sm
nginx {action} {action-params}

.SH DESCRIPTION
SM Framework Open Source Nginx Extension

.SH Actions

.TP 13
.B service
Manage the Nginx service.

.TP 13
.B server
Manage Nginx server configurations.

.TP 13
.B package
Manage the Nginx package.

.TP 13
.B configure
Replace /etc/nginx with the active installation configuration directory.

.TP 13
.B man
Display this man page
