#!/bin/sh

haproxy_initialize()
{
  package_dependencies=( pcre )

  package_definition \
    base_url "http://haproxy.1wt.eu/download/${package_version%.*}/src/" \
    docs_url "http://haproxy.1wt.eu/download/${package_version%.*}/doc/configuration.txt"

  service_flags+=( -f "/etc/haproxy/haproxy.cfg" )
  service_start_flags+=( -p "${service_pid_file}" -D )
  service_restart_flags+=( -p "${service_pid_file}" )
  service_stop_flags+=( )

  service_run_as_root_flag=1
}

haproxy_configure()
{
  # We build generic since the Makefile.osx doesn't appear to work
    if os_is_darwin
    then
      copy_file --force "Makefile.osx" to "Makefile"

      make_flags=(
        PREFIX="${install_path}"
        TARGET=generic
        USE_KQUEUE=1
        USE_POLL=1
        PCREDIR="${active_path}"
        SBINDIR="${install_path}/bin"
        USE_STATIC_PCRE=1
      )
    elif os_is_linux
    then
      make_flags=(
        PREFIX="${install_path}"
        PCREDIR="${active_path}"
        SBINDIR="${install_path}/bin"
        USE_STATIC_PCRE=1
      )

      # TODO: TPROXY is only availablle in kernels 2.6.28 and newer, check.
      # if os_kernel_version >= 2.6.28
      # then
      make_flags+=(USE_LINUX_TPROXY=1)
      # fi

      # TODO: Add in the check below
      # if os_kernel_version >= 2.6
      # then
         make_flags+=(TARGET=linux26)
      # else
      #   make_flags+=(TARGET=generic)
      # fi
    else
      make_flags=(
        PREFIX="${install_path}"
        PCREDIR="${active_path}"
        SBINDIR="${install_path}/bin"
        USE_STATIC_PCRE=1
        TARGET=generic
      )
    fi

    make_install_flags=( install ${make_flags[@]})
    make_flags+=( -j$(os_cpu_count) )

    make "${make_flags[@]}"
}

haproxy_postinstall()
{
  if user_is_root
  then
    if os_is_linux
    then
      if command_exists iptables
      then
        if ! file_contains "/etc/rc.local" '--set-mark 1'
        then
          note "You can append the following iptables config to /etc/rc.local:"\
          "\n# HAProxy"\
          "\niptables -t mangle -N DIVERT"\
          "\niptables -t mangle -A PREROUTING -p tcp -m socket -j DIVERT"\
          "\niptables -t mangle -A DIVERT -j MARK --set-mark 1"\
          "\niptables -t mangle -A DIVERT -j ACCEPT"\
          "\nip rule add fwmark 1 lookup 100"\
          "\nip route add local 0.0.0.0/0 dev lo table 100"\
          "\n# HAProxy"
        fi
      else
        true # No warning as we are not actually doing anything.
        # warn "The iptables command was not found, skipping iptables configuration."
      fi

      note "If you have an HAProxy pair running with heartbeat then you should"\
      " have an extenal floating virtual IP (VIP) and an internal floating IP"\
      "(FIP) for the default gateway. Then for internal servers you may also need"\
      " an additional IPTables Rule to masquerade internal traffic on the VIP, eg.
      iptables -t nat -A POSTROUTING -s 192.168.1.0/255.255.255.0 -j MASQUERADE\n"\
      "Many thanks to 'Malcom Turnbull' for this information in a blog comment."
    else
      warn "Skipping iptables configuration as the user is not running as root."
    fi

    note "You might also consider configuring forwarding and redirects in"\
      "/proc/sys/net/ipv4:"\
      "\necho 1 > /proc/sys/net/ipv4/conf/all/forwarding"\
      "\necho 1 > /proc/sys/net/ipv4/conf/all/send_redirects"\
      "\necho 1 > /proc/sys/net/ipv4/conf/eth0/send_redirects"

    note "Consider adjusting the max fd for the haproxy system:"\
         "\necho '*       soft    nofile  1024' >> /etc/security/limits.conf"\
         "\necho '*       hard    nofile  65535' >> /etc/security/limits.conf"\
         "\necho 65535 > /proc/sys/fs/file-max"

    if file_exists "/etc/haproxy/haproxy.cfg"
    then
      note "Skipping installation of haproxy.cfg as /etc/haproxy/haproxy.cfg"\
        "already exists"
    else
      if template_exists "haproxy/haproxy.cfg"
      then
        install_template "haproxy/haproxy.cfg" to "/etc/haproxy/haproxy.cfg" mode 0644
      else
        warn "Not installing the haproxy.cfg template as it does not exist..."\
          "This indicates something is wrong in the extension."
      fi
    fi

    if file_exists"/etc/haproxy/haproxy.cfg"
    then
      seed_template "/etc/haproxy/haproxy.cfg" \
        service_user "${service_user}"
    else
      warn "Not seeding temlpate /etc/haproxy/haproxy.cfg as the file is missing"
    fi

    # TODO: User config...???
  fi
}
