#!/bin/sh

haproxy_configure()
{
  # We build generic since the Makefile.osx doesn't appear to work
  if os is darwin
  then
    files copy force from "Makefile.osx" to "Makefile"

    make_flags=(
    PREFIX="${install_path}"
    TARGET=generic
    USE_KQUEUE=1
    USE_POLL=1
    PCREDIR="${active_path}"
    SBINDIR="${install_path}/bin"
    USE_STATIC_PCRE=1
    USE_PCRE=1 
    USE_OPENSSL=1 
    USE_ZLIB=1
    )
  elif os is linux
  then
    make_flags=(
    USE_PCRE=1 
    USE_OPENSSL=1 
    USE_ZLIB=1
    PREFIX="${install_path}"
    PCREDIR="${active_path}"
    SBINDIR="${install_path}/bin"
    ADDINC=-I"${active_path}/include"
    ADDLIB=-I"${active_path}/lib"
    USE_STATIC_PCRE=1
    )

    # TODO: TPROXY is only availablle in kernels 2.6.28 and newer, check.
    # if os_kernel_version >= 2.6.28
    # then
    make_flags+=(USE_LINUX_TPROXY=1)
    # fi

    # TODO: Add in the check below
    # if os_kernel_version >= 2.6
    # then
    make_flags+=(TARGET=linux2628)
    # else
    #   make_flags+=(TARGET=generic)
    # fi
  else
    make_flags=(
    PREFIX="${install_path}"
    PCREDIR="${active_path}"
    SBINDIR="${install_path}/bin"
    USE_STATIC_PCRE=1
    TARGET=generic
    )
  fi

  typeset -ga make_install_flags
  make_install_flags=( install ${make_flags[@]} )

  make_flags+=( -j$(os cpu count) )

  make ${make_flags[@]} > build.log 2>&1 || error \
      "Compilation of ${package_name} ${package_version} failed! " "$PWD/build.log"
}

haproxy_postinstall()
{
    echo "Be sure to run haproxy configure."
}
