#!/bin/sh

parse_args() {
	local token
	while (( $# ))
	do
		token=$1 ; shift
		case "${token}" in
			(etcd) true ;; # Ignore the first CLI parameter
		  (client_ip) client_ip=$1 ; shift ;;
	    (peer_ip) peer_ip=$1 ; shift ;;
      (peer_client_port) peer_client_port=$1 ; shift ;;
		  (peer_server_port) peer_server_port=$1 ; shift ;;
	    (client_port) client_port=$1 ; shift ;;
      (server_port) server_port=$1 ; shift ;;
		  (peers) peers=$1 ; shift ;;
	    (*) log fail "Unknown command line argument ${token}" ;;
    esac
  done
}

etcd_prefetch() {
	package define \
		base_url "https://github.com/coreos/etcd/releases/download/v${package_version}" \
    file "etcd-v${package_version}-Linux-x86_64.${archive_format}" \
    dir "etcd-v${package_version}-Linux-x86_64" \
		checksum_url "https://127.0.0.1/" # ... 
}

etcd_configure() {
	true # nothing to do
}

etcd_build() {
	true # nothing to do
}

etcd_install() {
	trace_filter etcd || set -o xtrace
	mkdir -p ${install_path}/bin
	chmod 0755 ${install_path}/bin

	for file in etcd etcdctl
	do 
		cp ./${file} ${install_path}/bin/${file}
		chmod a+x ${install_path}/bin/${file}
	done
}

etcd_postinstall() {
	mkdir -p /etc/etcd/

	if ! file exists /etc/etcd/etcd.conf
	then
		template install etcd/etcd.conf \
			to /etc/etcd/etcd.conf \
			mode 0644
	fi

	if ! file exists /etc/init.d/etcd
	then
		template install etcd/init.d \
			to /etc/init.d/etcd \
			owner root:root \
			mode 0755
	fi
}

read_pidfile() {
	if [[ -s ${pid_file} ]]
	then pid=$(head -1 ${pid_file})
	else pid=0
	fi

	[[ -n "${pid}" ]] && (( pid > 0 )) || pid=0
}
